using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace CompressShaders
{
	static class LanguageCodes
	{
		record struct Row
		{
			public string keySource;
			public uint keyValue;
			public int code;
			public string name;
		}

		static uint makeKey( string str )
		{
			if( str.Length > 4 )
				throw new ArgumentException();
			uint k = 0;
			int shift = 0;
			foreach( char c in str )
			{
				if( c >= 0x80 )
					throw new ArgumentException();
				uint u = (uint)c;
				k |= ( u << shift );
				shift += 8;
			}
			return k;
		}

		static IEnumerable<Row> load( string path )
		{
			using var stm = File.OpenText( path );
			while( true )
			{
				string? line = stm.ReadLine();
				if( null == line )
					break;
				if( string.IsNullOrWhiteSpace( line ) )
					continue;
				string[] fields = line.Split( '\t' );
				yield return new Row()
				{
					keySource = fields[ 0 ],
					keyValue = makeKey( fields[ 0 ] ),
					code = int.Parse( fields[ 1 ] ),
					name = fields[ 2 ]
				};
			}
		}

		static void writeCpp( string inl, Row[] data )
		{
			// TODO [very low]: sort them by the key here, then in C++ use binary search instead of the hash map
			using var stm = File.CreateText( inl );
			stm.WriteLine( "// This file is generated by a tool, from the `languageCodez.tsv` file in this repository" );
			foreach( Row row in data )
              stm.WriteLine( "Lang{{ 0x{0:X}, {1}, {2} }},", row.keyValue, row.code, cppStringLiteralUtf8( row.name ) );
		}

		static string cppStringLiteralUtf8( string value )
		{
			byte[] utf8 = Encoding.UTF8.GetBytes( value );
			StringBuilder sb = new StringBuilder( utf8.Length * 4 + 2 );
			sb.Append( '"' );
			foreach( byte b in utf8 )
				sb.Append( "\\x" ).Append( b.ToString( "X2" ) );
			sb.Append( '"' );
			return sb.ToString();
		}

		static readonly CultureInfo ci = new CultureInfo( "en-US", false );
		static string titleCase( this string name ) =>
			ci.TextInfo.ToTitleCase( name.ToLower( ci ) );

		static string stableEnumNameSource( string keySource ) => keySource switch
		{
			"en" => "english",
			"zh" => "chinese",
           "yue" => "cantonese",
			"de" => "german",
			"es" => "spanish",
			"ru" => "russian",
			"ko" => "korean",
			"fr" => "french",
			"ja" => "japanese",
			"pt" => "portuguese",
          "tr" => "turkish",
			"pl" => "polish",
			"ca" => "catalan",
			"nl" => "dutch",
			"ar" => "arabic",
			"sv" => "swedish",
			"it" => "italian",
			"id" => "indonesian",
			"hi" => "hindi",
			"fi" => "finnish",
			"vi" => "vietnamese",
			"iw" => "hebrew",
			"uk" => "ukrainian",
			"el" => "greek",
			"ms" => "malay",
			"cs" => "czech",
			"ro" => "romanian",
			"da" => "danish",
			"hu" => "hungarian",
			"ta" => "tamil",
			"no" => "norwegian",
			"th" => "thai",
			"ur" => "urdu",
			"hr" => "croatian",
			"bg" => "bulgarian",
			"lt" => "lithuanian",
			"la" => "latin",
			"mi" => "maori",
			"ml" => "malayalam",
			"cy" => "welsh",
			"sk" => "slovak",
			"te" => "telugu",
			"fa" => "persian",
			"lv" => "latvian",
			"bn" => "bengali",
			"sr" => "serbian",
			"az" => "azerbaijani",
			"sl" => "slovenian",
			"kn" => "kannada",
			"et" => "estonian",
			"mk" => "macedonian",
			"br" => "breton",
			"eu" => "basque",
			"is" => "icelandic",
			"hy" => "armenian",
			"ne" => "nepali",
			"mn" => "mongolian",
			"bs" => "bosnian",
			"kk" => "kazakh",
			"sq" => "albanian",
			"sw" => "swahili",
			"gl" => "galician",
			"mr" => "marathi",
			"pa" => "punjabi",
			"si" => "sinhala",
			"km" => "khmer",
			"sn" => "shona",
			"yo" => "yoruba",
			"so" => "somali",
			"af" => "afrikaans",
			"oc" => "occitan",
			"ka" => "georgian",
			"be" => "belarusian",
			"tg" => "tajik",
			"sd" => "sindhi",
			"gu" => "gujarati",
			"am" => "amharic",
			"yi" => "yiddish",
			"lo" => "lao",
			"uz" => "uzbek",
			"fo" => "faroese",
			"ht" => "haitian creole",
			"ps" => "pashto",
			"tk" => "turkmen",
			"nn" => "nynorsk",
			"mt" => "maltese",
			"sa" => "sanskrit",
			"lb" => "luxembourgish",
			"my" => "myanmar",
			"bo" => "tibetan",
			"tl" => "tagalog",
			"mg" => "malagasy",
			"as" => "assamese",
			"tt" => "tatar",
			"haw" => "hawaiian",
			"ln" => "lingala",
			"ha" => "hausa",
			"ba" => "bashkir",
			"jw" => "javanese",
			"su" => "sundanese",
			_ => throw new ArgumentException( $"Unsupported language code \"{keySource}\"" )
		};

		static void writeCs( string cs, Row[] data )
		{
			using var stm = File.CreateText( cs );
			stm.WriteLine( @"// This file is generated by a tool, from the `languageCodez.tsv` file in this repository
namespace Whisper
{
	/// <summary>Supported languages</summary>
	/// <remarks>The values of this enum are zero-padded ASCII strings.<br/>
	/// It seems OpenAI tried to implement ISO 639-1, but they used the version of the standard from 1988.</remarks>
	public enum eLanguage: uint
	{" );

			foreach( Row row in data )
			{
               string tc = stableEnumNameSource( row.keySource ).titleCase();
				stm.WriteLine( "		/// <summary>{0}</summary>", row.name );
				tc = Regex.Replace( tc, @"\s+", string.Empty );
				stm.WriteLine( "		{0} = 0x{1:X},  // \"{2}\"", tc, row.keyValue, row.keySource );
			}
			stm.Write( @"	}
}" );
		}

		static void produce( string tsv, string inl, string cs )
		{
			Row[] data = load( tsv ).OrderBy( r => r.name ).ToArray();
			writeCpp( inl, data );
			writeCs( cs, data );
		}

		public static void produce( string solutionRoot )
		{
			string tsv = Path.Combine( solutionRoot, "Whisper\\Whisper\\languageCodez.tsv" );
			string inl = Path.Combine( solutionRoot, "Whisper\\Whisper\\languageCodez.inl" );
			string cs = Path.Combine( solutionRoot, "WhisperNet\\API\\eLanguage.cs" );
			produce( tsv, inl, cs );
		}
	}
}