<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Platforms>x64</Platforms>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="..\..\x64\$(Configuration)\Whisper.dll" Link="Whisper.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\..\Native\WhisperCppBackend\build-cpu\bin\WhisperCppBackendCpu.dll" Link="WhisperCppBackendCpu.dll" Condition="Exists('..\..\Native\WhisperCppBackend\build-cpu\bin\WhisperCppBackendCpu.dll')">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\..\Native\WhisperCppBackend\build-cuda\bin\WhisperCppBackendCuda.dll" Link="WhisperCppBackendCuda.dll" Condition="Exists('..\..\Native\WhisperCppBackend\build-cuda\bin\WhisperCppBackendCuda.dll')">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="$(CUDA_PATH)\bin\x64\cublas64_13.dll" Link="cublas64_13.dll" Condition="'$(CUDA_PATH)' != '' And Exists('$(CUDA_PATH)\bin\x64\cublas64_13.dll')">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="$(CUDA_PATH)\bin\x64\cublasLt64_13.dll" Link="cublasLt64_13.dll" Condition="'$(CUDA_PATH)' != '' And Exists('$(CUDA_PATH)\bin\x64\cublasLt64_13.dll')">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="$(CUDA_PATH)\bin\x64\cudart64_13.dll" Link="cudart64_13.dll" Condition="'$(CUDA_PATH)' != '' And Exists('$(CUDA_PATH)\bin\x64\cudart64_13.dll')">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\WhisperNet\WhisperNet.csproj" />
	</ItemGroup>
</Project>
